_BASE_: "./train_config.yaml"
INPUT:
  EVAL_BETA: 0.0
  HISTORY_ON: True
  NUM_HISTORY: 4
DATASETS:
  TEST: ("robotcar_eval",)
MODEL:
  # WEIGHTS: "./output/mvdnet/model_final.pth"
  # WEIGHTS: "./MVDNet_weights/moddel_final_clear_weather.pth"
  WEIGHTS: "./MVDNet_weights/moddel_final_fog_weather.pth"
  # WEIGHTS: "./MVDNet_weights/moddel_final_mix_weather.pth"
